### ISSUE TITLE
Temp file

### ISSUE THREAD

**Issue by cfernandomaciel** [zdenop/tesseract-ocr-qt4gui#1]
What's up with the temp file? When I build the project, it returns a temp/qrc_qt4tesseract.cpp file not found.

**Comment by zdenop** [comment]
How did you build project?

**Comment by cfernandomaciel** [comment]
opened it with Qtcreator.
I already found the trouble, I had set qt creator to make a shadow build,
in that case it didn't find the temp folder.

Everything's working now.

Thank you.

C. Fernando Maciel
System's Analyst / Reverse Engineer
Phone: +55(48)8833-9801
Blog <#SafeHtmlFilter_SafeHtmlFilter_> |
Company<#SafeHtmlFilter_SafeHtmlFilter_>

**Comment by Zieng** [comment]
@cfernandomaciel Hello, I met the same problem as you. Can you tell me how do you solve the problem? I don't quite understand what do you mean you made a shadow build. Thanks in advance.

**Comment by Zieng** [comment]
I solved my problem. It because missing the `qt4tesseract_en.qm` file.
